### ISSUE TITLE
S3 methods vs dedicated functions for explain

### ISSUE THREAD

**Issue by krzjoa** [ModelOriented/DALEXtra#82]
Hi,

I have a question, just out of curiosity.

I can see that in the `{DALEX}` package you initially inteded to use `explain` as a S3 method, as [`explain.default`](https://github.com/ModelOriented/DALEX/blob/b85520734f2590f2631f54e7853294bbf77127dc/R/explain.R#L126) suggests. It would even be compatible with the [`explain`](https://generics.r-lib.org/reference/explain.html) method in the [`{generics}`](https://github.com/r-lib/generics/#usage) package. However, in the `{DALEXtra}` package you created a set of dedicated methods such as `explain_tidymodels` or `explain_mlr`.

Why didn't you decide to create specialised explain method versions (like `explain.model_fit`, `explain.workfkow`, `explain.WrappedModel` etc.) in the same manner as it was done in the case of the [`model_info`](https://github.com/ModelOriented/DALEXtra/blob/HEAD/R/model_info.R) method?

I'm asking because I'd like to create a connector between `{keras}` for R and `{DALEX}`.
Personally, I'd prefer to make a S3 method for these models.

**Comment by maksymiuks** [comment]
Hi,

thanks for your question, I'm glad to explain :)

`explain` function was never intended to be a proper generic. The idea of having an `explain.default` was only a workaround for some of the name collisions rather than a long-term plan or support for the `generics` package. The true idea of `explain` function is that it should accept everything, regardless of the input, and then support the user with a set of predefined predict functions (yhat) that are proper S3 generics. It adds flexibility as a user can pass to explain arbitrary objects and the only requirement is passing a predict_function, as a quick example, you may want to explain a stacked model in the form of a plain list, it could then look like that:
```
stacked_model <- list(model_1, model_2, model_3)

explain(stacked_model, data, y, predict_function = function(model, newdata) mean(sapply(yhat(model, newdata))
``` 
which wouldn't be possible had we simply had an `explain` function itself as a S3 method (or would be with a correct default but this way is simply cleaner).

That said, I agree that `DALEXtra` might have gone a slightly different path with explicit function for various models, but this is only a fasade. If you take a look at the actual code of those functions you will see that except for performing a few checks, it simply calls an explain function from DALEX and allows R to find appropriate yhat by itself, no deeper preprocessing is done there. Explicit names are there only from a user experience perspective. It appears in the google search, CRAN search etc. It directly communicates to the potential user that, for instance, mlr3 models are supported and can be used with DALEX out of the box, rather than making the user look whether there is an appropriate yhat method for this package. It simply directly communicates what one could achieve with this package.

Furthermore, it started with Python models (keras and sk learn) that don't have human-readable classes and thus required an explicit explain function to handle the python environment first (rather than splitting it into separate functions).

I hope this answers your question and satisfies your curiosity. Please don't hesitate to ask if there is anything more I could explain. Also wish you all the best in your project!

**Comment by krzjoa** [comment]
Thank you for the detailed clarification, @maksymiuks! :sunglasses:
